services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: cucabeludo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
